# Generated by Django 4.0.5 on 2022-06-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_rename_track_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_name',
        ),
    ]
