# Generated by Django 4.0.5 on 2022-07-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0004_artist_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
