# Generated by Django 4.0.5 on 2022-06-30 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0004_album_added_to_database_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='added_to_database_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
