# Generated by Django 4.0.5 on 2022-07-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0007_album_artist_alter_artist_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist2', to='Album.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist1', to='Album.artist'),
        ),
    ]
