# Generated by Django 4.0.5 on 2022-07-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0008_artist_artist_alter_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='artist_name',
        ),
    ]
