# Generated by Django 4.0.5 on 2022-07-01 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0009_rename_artist_artist_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='track_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='album',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='This Album Has No Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='Album.artist'),
        ),
    ]
